services:
  system-monitor:
    ports:
      - 8081:8080
    image: geeksheik9/system-monitor:v0.0.5.8-alpha
    container_name: system-monitor
    build: .
    volumes:
      - /temp:/sys/class/thermal/thermal_zone*/temp