services:
  system-monitor:
    ports:
      - 8081:8080
    image: geeksheik9/system-monitor:latest
    container_name: system-monitor
    volumes:
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp